langauge: generic
sudo: required
addons:
  ssh_known_hosts: 137.184.160.164
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- docker build -t ldawit/docker-react  -f Dockerfile.dev .
script:
- docker run -e CI=true ldawit/docker-react npm run test
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
