langauge: generic 
sudo: required

services:
  - docker
before_install:
  - docker build -t ldawit/docker-react  -f Dcokerfile.dev .

script:
  - docker run -e CI=true ldawit/docker-react npm run test