name: release-publish
env:
  REGISTRY: "registry.digitalocean.com/docker-react"
  SERVICE: "docker-react"
  NAMESPACE: "test"
on:
  release:
    types: 
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: env output
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        name: git checkout
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $REGISTRY/$SERVICE:${{ github.event.release.tag_name }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        env: 
          DIGITALOCEAN_ACCESS_TOKEN : ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        # with:
        #   token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$SERVICE:${{ github.event.release.tag_name }}